classtimeConversion/urls.py
from django.urls import path
from . import views

app_name = 'classtimeConversion'

urlpatterns = [
    path('', views.months_calculation, name='months-calculation')
]

cohorteTimer/urls.py
from django.urls import path
from . import views

app_name = 'cohorteTimer'

urlpatterns = [
    path('', views.record_time, name='record-time'),
]

trackcamp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('record/', include('cohorteTimer.urls', namespace='cohorte-timer')),
    path('monthcalculate/', include('classtimeConversion.urls', namespace='classtime-conversion')),
]

classtimeConversion/models.py
from django.db import models

# Create your models here.

cohorteTimer/models.py
from django.db import models
from django.utils import timezone

class Program(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    creation_date = models.DateTimeField(default=timezone.now)
    update_date = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.name
    
class Teacher(models.Model):

    class Position(models.TextChoices):
        TRAINER = 'F', 'Formador'
        COTRAINER = 'CF', 'Coformador'

    name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    position = models.CharField(max_length=2,choices=Position.choices, default=Position.TRAINER)

    def __str__(self):
        return self.name

class Cohorte(models.Model):
    name = models.CharField(max_length=250)
    start_date = models.DateField
    end_date = models.DateField
    duration = models.IntegerField
    number_hours = models.IntegerField
    program = models.ForeignKey(Program, on_delete=models.CASCADE)
    kind = models.CharField(max_length=250)

    def __str__(self):
        return self.name

class TeacherCohorte(models.Model):
    id_teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    id_cohorte = models.ForeignKey(Cohorte, on_delete=models.CASCADE)

classtimeConversion/forms.py
from django import forms

class RegisterForm(forms.Form):
    hours_total_number = forms.IntegerField(label="Número Total de horas del curso", widget=forms.NumberInput(attrs={'class':'form-control', 'placeholder': 'Horas totales de la formación'}))
    hourly_intensity = forms.IntegerField(label="Intensidad horaria semanal", widget=forms.NumberInput(attrs={'class':'form-control', 'placeholder': 'Total de horas a la semana'}))

cohorteTimer/forms.py
from django import forms
from django.forms import widgets
from .models import Cohorte

class RegisterForm(forms.Form):
    #name_cohorte = forms.CharField(max_length=25)
    #name_trainer = forms.CharField(max_length=25)
    #name_cotrainer = forms.CharField(max_length=25)
    duration_cohorte = forms.IntegerField(label="Duranción de la cohorte", widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'Cantidad de meses totales'}))
    start_cohorte = forms.DateField(label="Fecha de inicio de cohorte", widget=forms.widgets.DateInput(attrs={'class':'form-control','type': 'date'}))

classtimeConversion/views.py
from django.shortcuts import render
from .forms import RegisterForm

def months_calculation (request):
    hour_month_aprox = 30 * 24
    month_week = 4

    if request.method == "POST":
        form = RegisterForm(data = request.POST)

        if form.is_valid():

            #Valores de los campos del formulario
            
            total_hours_course = form.cleaned_data['hours_total_number']

            week_hourly_intensity = form.cleaned_data['hourly_intensity']

            #Realizamos sus respectivas operaciones
            total_hours_delay = total_hours_course / week_hourly_intensity

            #month_delay_aprox = round(total_hours_delay / hour_month_aprox)
            month_delay_aprox = round(total_hours_delay / month_week)

            return render(request, 'month_calculate.html',{'form': form, 'month_delay_aprox':month_delay_aprox})
            

    else: 
        form = RegisterForm()
    
    return render(request, 'month_calculate.html', {'form': form})

cohorteTimer/views.py
from django.shortcuts import render
from .forms import RegisterForm

from datetime import datetime, timedelta, date
import holidays

def record_time(request):
    if request.method == "POST":
        form = RegisterForm(data = request.POST)
        
        if form.is_valid():
            start_date = form.cleaned_data['start_cohorte']
            cohorte_duration = form.cleaned_data['duration_cohorte']
            end_time = time_cohorte(start_date, cohorte_duration)
            print("Dia de finalización ",end_time.weekday())
            festives_days = get_colombian_festivities(start_date,end_time)

            end_time += timedelta(days=festives_days)

            if end_time.weekday() == 5:
                end_time = end_time + timedelta(days=2)
            elif end_time.weekday() == 6:
                end_time = end_time + timedelta(days=1)

            return render(request, "register.html", {'cohorte_duration': cohorte_duration, 'start_date': start_date, 'end_time':end_time, 'festives_days': festives_days})
    else:
        form = RegisterForm()     
    return render(request, 'register.html', {'form': form})

# función para el calculo de cohorte
# Inputs: Fecha inicio, duracion_cohorte 
def time_cohorte(start_date, cohorte_duration):
    #Comprobamos que la información ingresada por el usuario tenga la fecha correcta
    #date = datetime.strptime(start_date, "%d/%m/%Y")
    # Convertimos los meses ingresados en dias
    #Cantidad de dias estandar en un mes (se tienen en cuenta todos para poder dar avance con el tema)
    month_days = 30
    month_days_totales = cohorte_duration * month_days
    print(month_days_totales)
    #Guardamos en variable la fecha final
    end_date = timedelta(days=month_days_totales)
    # Sumamos los valores para hacer el calculo
    future_date = start_date + end_date
    number_day = future_date.weekday()
    print(number_day)
    
    return future_date

#Crear la función que determine los días festivos en Colombia
def get_colombian_festivities(start_date, end_date):
    current_year = datetime.now().year

    festivals = holidays.CO(years=current_year)

    date_festivals = festivals.keys()

    segment_date = [fecha for fecha in date_festivals if start_date <= fecha <= end_date]
    count_segment_date = len(segment_date)
    return count_segment_date
    

classtimeConversion/templates/month_calculate.html
{% extends "base.html" %}
{% block title %}Month Calculate{% endblock %}
{% block content %}
{% include 'nav.html' %}
<section class="container flex-grow-1 card text-center">
    <h1 class="d-flex align-self-center">Información general</h1>
    <p>Muestra la cantidad de meses aproximada que demorara una cohorte o formación.</p>
    <hr class="border border-primary border-3 opacity-75">
    <form method="post">
        {{ form.as_p }}
        
        <input type="submit" value="Enviar" class="btn btn-outline-primary">
        {% csrf_token %}
    </form>
    <section>
        {% if month_delay_aprox %}
            <h3>Resultado:</h3>
            {{ month_delay_aprox }} Meses.
        {% endif %}
    </section>
</section>
{% include 'footer.html'%}
{% endblock %}

classtimeConversion/templates/month_result.html
{% extends "base.html" %}
{% block title %}Month Calculate{% endblock %}
{% block content %}
    <h1>prueba</h1>
    {{ month_delay_aprox }} Meses.
{% endblock %}

cohorteTimer/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  </head>
</head>
<body>
    <main class="p-2 d-flex justify-content-center align-items-center flex-column" style="min-height: 100vh;">
        {% block content %}
        {%  endblock %}
    </main>
</body>
</html>

cohorteTimer/templates/footer.html
<footer class="footer mt-auto fixed-bottom">
    <div class="container text-center">
        <h5>Hecho en 🇨🇴 por @arizamoisesco</h5>
        <h5>{% now "Y" %}</h5>
    </div>
</footer>

cohorteTimer/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark container-fluid">
    <div class="container-fluid">
      <ul class="nav justify-content-center nav-tabs">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'cohorteTimer:record-time' %}">Duración cohorte</a></li>
        <li class="nav-item"><a class="nav-link active" href="{% url 'classtimeConversion:months-calculation' %}">Calcular meses</a></li>
      </ul>
    </div> 
  </nav>

cohorteTimer/templates/register.html
{% extends "base.html" %}
{% block title %}Cohorte Timer{% endblock %}
{% block content %}
    {% include 'nav.html' %}
    <section class="container flex-grow-1 card text-center">
        <h1 class="d-flex align-self-center">Información general</h1>
        <p> Determina la fecha de inicio y finalización de las cohortes teniendo en cuenta la cantidad de festivos que entre los meses. </p>
        <hr class="border border-primary border-3 opacity-75">
        <form  method="post" >
            {{ form.as_p }}
            {% csrf_token %}
            {% if not end_time %}
                <input type="submit" value="Enviar" class="btn btn-outline-primary">
            {% endif %}
        </form>

        {% if end_time %}
            <h2>Tiempo de la cohorte</h2>
            <ul class='list-unstyled'>
                <li>Cantidad de meses de duración de la cohote: {{ cohorte_duration }} meses</li>
                <li>Fecha de inicio {{ start_date }}</li>
                <li>Fecha de finalización {{ end_time }}</li>
                <li>Cantidad de dias festivos: {{ festives_days }}</li>
            </ul>
            <a class="btn btn-outline-success" href="{% url 'cohorteTimer:record-time' %}">Ingresar nueva fecha </a>
        {% endif %}
    </section>
    {% include 'footer.html' %}
{% endblock %}

cohorteTimer/templates/result.html
{% extends "base.html" %}
{% block title %}Resultado{% endblock %}
{% block content %}
<h1>El resultado de la cohorte es {{ dato }}</h1>
{% endblock %}